name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows manual triggers

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Replace Secrets in Code
        run: |
          sed -i "s|GOOGLE_CLIENT_ID|'${{ secrets.GOOGLE_CLIENT_ID }}'|g" script.js

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4